/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FontFamily = IDL.Variant({
  'arial' : IDL.Null,
  'sansSerif' : IDL.Null,
  'verdana' : IDL.Null,
  'openDyslexic' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'fontFamily' : FontFamily,
  'highContrast' : IDL.Bool,
  'fontSize' : IDL.Nat,
  'lineSpacing' : IDL.Nat,
  'letterSpacing' : IDL.Nat,
});
export const Time = IDL.Int;
export const PointsTransaction = IDL.Record({
  'timestamp' : Time,
  'points' : IDL.Nat,
  'eventType' : IDL.Text,
});
export const StudySession = IDL.Record({
  'subject' : IDL.Text,
  'date' : Time,
  'durationMinutes' : IDL.Nat,
});
export const PdfMetadata = IDL.Record({
  'name' : IDL.Text,
  'blobId' : IDL.Text,
  'sizeBytes' : IDL.Nat,
  'uploadedAt' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGlossaryTerm' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addPdfMetadata' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'addPoints' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'addTip' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deletePdfMetadata' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGlossary' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getPointsHistory' : IDL.Func([], [IDL.Vec(PointsTransaction)], ['query']),
  'getStudySessions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(StudySession)],
      ['query'],
    ),
  'getTips' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserPdfs' : IDL.Func([], [IDL.Vec(PdfMetadata)], ['query']),
  'getUserPoints' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logStudySession' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchGlossary' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FontFamily = IDL.Variant({
    'arial' : IDL.Null,
    'sansSerif' : IDL.Null,
    'verdana' : IDL.Null,
    'openDyslexic' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'fontFamily' : FontFamily,
    'highContrast' : IDL.Bool,
    'fontSize' : IDL.Nat,
    'lineSpacing' : IDL.Nat,
    'letterSpacing' : IDL.Nat,
  });
  const Time = IDL.Int;
  const PointsTransaction = IDL.Record({
    'timestamp' : Time,
    'points' : IDL.Nat,
    'eventType' : IDL.Text,
  });
  const StudySession = IDL.Record({
    'subject' : IDL.Text,
    'date' : Time,
    'durationMinutes' : IDL.Nat,
  });
  const PdfMetadata = IDL.Record({
    'name' : IDL.Text,
    'blobId' : IDL.Text,
    'sizeBytes' : IDL.Nat,
    'uploadedAt' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGlossaryTerm' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addPdfMetadata' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'addPoints' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'addTip' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deletePdfMetadata' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGlossary' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getPointsHistory' : IDL.Func([], [IDL.Vec(PointsTransaction)], ['query']),
    'getStudySessions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(StudySession)],
        ['query'],
      ),
    'getTips' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserPdfs' : IDL.Func([], [IDL.Vec(PdfMetadata)], ['query']),
    'getUserPoints' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logStudySession' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchGlossary' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };